### ISSUE TITLE
fix boolean operators for arrays

### ISSUE THREAD

**Issue by masonproffitt** [iris-hep/func_adl.uproot#13]
You can't use `and` and `or` with numpy arrays or you will get errors like `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`. I always use bitwise operators like `&` and `|` to accomplish this when dealing with awkward or numpy arrays.

**Comment by masonproffitt** [comment]
Actually, it would be more proper to use something like `numpy.logical_and()`, `numpy.logical_or()`, and `numpy.logical_not()`, but that's more work to implement. I'll take the easier way for now in #14  and leave this open.

**Comment by gordonwatts** [comment]
I have to say - I ended up using `logical_and` and `logical_or` - I hate it when using numpy because it makes an expression feel rather unnatural and large. But it seemed to be the best way to assure what I wanted happened.

**Comment by masonproffitt** [comment]
In as of version 0.11
